### ISSUE TITLE
How do you run the web app?

### ISSUE THREAD

**Issue by willbarkoff** [CoursesPlus/Labby#1]

**Comment by thatoddmailbox** [comment]
You need to install [node.js](https://nodejs.org/en/). (I am not sure, but the student laptops _might_ already have Node installed) Then, clone the repo and run `npm install` from a command prompt/terminal open to the folder. This will install necessary dependencies.

Then, to start it, run `node runme.js` from the same command prompt/terminal. It should then be available in your browser on the webpage http://localhost:3000.

**Comment by thatoddmailbox** [comment]
I might also start up a staging server at some point that will just run the latest changes automatically, but it doesn't exist yet.

**Comment by willbarkoff** [comment]
Okay Thanks, I will tell you if it works.

**Comment by thatoddmailbox** [comment]
@nywillb I set up a cloud-ified staging server [here](http://labby-staging.azurewebsites.net/). **Do _not_ use that as the actual Labby site. It is for testing only, and might break at some point.** Do use it for testing or a quick demonstration or something like that. It should automagically update with the latest changes in GitHub, though it might take a minute or two.

**Comment by willbarkoff** [comment]
Is it possible to add bootswatch and remove the gradient?

**Comment by thatoddmailbox** [comment]
Yes, but you should put that in a separate issue. Labby already uses bootstrap, so adding bootswatch should be as easy as copying the code from bootstrapcdn.  

If you're talking about the navbar gradient, that was done by commits 356e1be and 1292870, so you should just be able to undo those.

**Comment by medensqui** [comment]
English pls? Aka step by step instructions?

**Comment by medensqui** [comment]
@thatoddmailbox

**Comment by thatoddmailbox** [comment]
@medensqui Just connect the frobulator to the wibbly-wobbly using parameter mode C.
1. GO TO [BOOTSTRAPCDN.COM](HTTP://BOOTSTRAPCDN.COM)
2. GO TO THE BOOTSWATCH PAGE
3. PICK A PRETTY THEME
4. WHEN YOU LIKE ONE, CLICK THE ARROW AND THEN COPY THE HTML CODE.
5. PASTE IT INTO THE HEADER FILE IN LABBY.
6. SAVE
7. COMMIT AND PUSH
8. WAIT IMPATIENTLY FOR MICROSOFT AZURE TO PICK UP THE CHANGES
9. ENJOY BOOTSWATCHNESS ON THE STAGING SITE

**For removing navbar gradient (not in caps because this !@#$=ing chromebook doesn't have a caps lock key and my finger hurts from holding shift)**
1. Look at 356e1be and 1292870
2. Undo what they did
3. Commit and push
4. While waiting for Azure, yell it @c20et for adding it
5. Be happy

**Comment by willbarkoff** [comment]
You just click where @thatoddmailbox said to earlier.

**Comment by willbarkoff** [comment]
Let's use yeti.

**Comment by medensqui** [comment]
@thatoddmailbox I MEANT FOR THE WEB APP

**Comment by medensqui** [comment]
YARG

**Comment by thatoddmailbox** [comment]
@nywillb Done.

@medensqui Ohhhh........ To access the **staging** server, go to [here](http://labby-staging.azurewebsites.net). Copy-pasted warnings: Do not use that as the actual Labby site. It is for testing only, and might break at some point. Do use it for testing or a quick demonstration or something like that. It should automagically update with the latest changes in GitHub, though it might take a minute or two.

Labby isn't actually a public thing yet.

**Comment by thatoddmailbox** [comment]
@nywillb YAY IT WORKED AND YETI LOOKS NICE AND SHINY!

**Comment by thatoddmailbox** [comment]
@medensqui OH WAIT YOU MEAN TO INSTALL NODE YOU WANT STEP BY STEP INSTRUCTIONS!

oops

I will add a Markdown file that has instructions.

**Comment by medensqui** [comment]
@thatoddmailbox YAY! So, labby.tk?

**Comment by thatoddmailbox** [comment]
@medensqui When I said Markdown file I meant wiki page.

**Comment by medensqui** [comment]
@thatoddmailbox YES AND FOR TERMINAL THINGY

**Comment by medensqui** [comment]
@thatoddmailbox Or daltonlabby.com? https://www.godaddy.com/domains/searchresults.aspx?checkAvail=1&domainToCheck=labby.com

**Comment by thatoddmailbox** [comment]
@medensqui Ummm.... maybe. I also have a free .me domain (you can too! get the GitHub student pack!), but I was planning to use that for something else...

**Comment by medensqui** [comment]
@thatoddmailbox Also, how's ur carbon copy of dalton planner going?

**Comment by thatoddmailbox** [comment]
@medensqui EW GODADDY NO WHY

**Comment by medensqui** [comment]
@thatoddmailbox I DO TOO

**Comment by medensqui** [comment]
@thatoddmailbox What else?

**Comment by thatoddmailbox** [comment]
@medensqui daltonlabby.me?

**Comment by medensqui** [comment]
@thatoddmailbox Where do I find all the benefits? Also, sure! I'll use my .me domain

**Comment by thatoddmailbox** [comment]
@medensqui [Here](https://education.github.com/pack), but don't get the domain yet!

**Comment by medensqui** [comment]
@thatoddmailbox But I mean, is Labby necessary? b/c of youcanbook.me?

**Comment by thatoddmailbox** [comment]
@medensqui which is why you shouldn't get the domain yet...

**Comment by medensqui** [comment]
@thatoddmailbox Ok, we need some benefits.

**Comment by thatoddmailbox** [comment]
@medensqui and to convince teachers to use it. Which is hard.

**Comment by willbarkoff** [comment]
How about schedule integration. Find common lab times automatically.

**Comment by thatoddmailbox** [comment]
@nywillb That could work, and you can download the scheduling data from the faculty part of schedules.dalton.

The problem is that the teacher would still have to opt-in to use labby

**Comment by medensqui** [comment]
@thatoddmailbox Yep. Here's youcanbook's free and paid features. If we can carry paid features over, it might entice people.

@nywillb Yay that could work. Oh shit look above

**Comment by medensqui** [comment]
@thatoddmailbox Oops forgot to link. https://youcanbook.me/pricing/

**Comment by thatoddmailbox** [comment]
@medensqui 
Answer to your question about my planner:
![screenshot 2015-10-25 at 3 32 17 pm](https://cloud.githubusercontent.com/assets/1904587/10717419/c19f4ef2-7b2d-11e5-9694-4eeb430e5692.png)
![screenshot 2015-10-25 at 3 30 49 pm](https://cloud.githubusercontent.com/assets/1904587/10717420/c1a40140-7b2d-11e5-9f3c-d33987c0d61e.png)

**Comment by thatoddmailbox** [comment]
@medensqui We could offer things youcanbook.me wants money for, but there are still some teachers that refuse to any online lab thing because their paper-based solution works.

**Comment by medensqui** [comment]
@thatoddmailbox OMG THAT LOOKS !@#$-ING INCREDIBLE. What's the domain?

Also, the .me is only for 1 year :cry:

**Comment by medensqui** [comment]
@thatoddmailbox Yeah, but labby doesn't need to be with all teachers. Make an easy editing interface w/ customizable themes and stuff and teachers will come (at least everyone who will use online software).

**Comment by willbarkoff** [comment]
Guys, let's keep the language in check.

**Comment by medensqui** [comment]
@nywillb https://www.law.cornell.edu/constitution/first_amendment

**Comment by thatoddmailbox** [comment]
@medensqui GEEZ OK CALM DOWN. The domain is [http://aserv-cloud.cloudapp.net/coursestest/](http://aserv-cloud.cloudapp.net/coursestest/), but it's on a whitelist. I can add you if you want.

That's true. 

Psst @medensqui... listen to @nywillb

**Comment by medensqui** [comment]
@thatoddmailbox Pls do

**Comment by medensqui** [comment]
@thatoddmailbox Psst https://www.law.cornell.edu/constitution/first_amendment

**Comment by thatoddmailbox** [comment]
@medensqui Psst... look at your comment again. :wink:

Ok, I will.

**Comment by willbarkoff** [comment]
What if we had a youcanbook.me import

**Comment by medensqui** [comment]
@nywillb Hmm that works I guess

**Comment by thatoddmailbox** [comment]
@medensqui That would work.. that way you don't use the labs. But you'd still have to convince them to switch.

**Comment by medensqui** [comment]
@thatoddmailbox ? Also what about the .me

It's only for one year :cry:

**Comment by thatoddmailbox** [comment]
@medensqui ...but then it doesn't cost _that_ much....

**Comment by willbarkoff** [comment]
We should have a masking redirect at labby.coursesplus.tk

**Comment by thatoddmailbox** [comment]
@medensqui what is your Dalton username? c19jf?

**Comment by thatoddmailbox** [comment]
@nywillb That sounds like a smart idea. Also, I just realized that our fast-paced discussion might have filled up your inbox. Sorry.

**Comment by willbarkoff** [comment]
That's ok and my dalton username is c20wb

**Comment by thatoddmailbox** [comment]
@nywillb Ok. Do you want me to add you to the list for the people using the planner thing?

**Comment by medensqui** [comment]
@thatoddmailbox Yes

**Comment by willbarkoff** [comment]
Yes

**Comment by willbarkoff** [comment]
Guys:

**Comment by thatoddmailbox** [comment]
@medensqui @nywillb I added you both to the list. Go to [here](http://aserv-cloud.cloudapp.net/coursestest/) and sign in with your Dalton account. It is still in beta, so things might not work. Use the smiley/frowny faces in the corner to send feedback. (please do)

**Comment by medensqui** [comment]
@thatoddmailbox So are you releasing it? And is davis going to be mildly inconvenienced?

**Comment by thatoddmailbox** [comment]
@medensqui @nywillb also it doesn't have a name. If you have an idea for a name, please tell me.

**Comment by medensqui** [comment]
SCHEDULES DOESNT WORK @thatoddmailbox

**Comment by medensqui** [comment]
@thatoddmailbox Dalton Workspace?

**Comment by thatoddmailbox** [comment]
@medensqui After the schedule view is working and someone comes up with a name for it, I will put up a GitHub repo and the code. It will then have a new shiny domain.

I KNOW SCHEDULES DOESN'T WORK

**Comment by willbarkoff** [comment]
The Dalton Plan

**Comment by medensqui** [comment]
@thatoddmailbox MY NAME IS PERFECT

@nywillb NO THAT WOULD NEED LABBY TO BE INTEGRATED AND SOME SORT OF HOUSE THING

**Comment by thatoddmailbox** [comment]
@medensqui Maybe. I'm not sure if it will be Dalton-only or not.

So far, the ideas have been:
- StudyHub
- StuderPlanner
- Dalton Workspace
- The Dalton Plan

**Comment by medensqui** [comment]
@thatoddmailbox Then what about Workspace? That's school neutral

Sent from FirstClass with my iPhone

**Comment by thatoddmailbox** [comment]
@medensqui workspace.me is taken...

**Comment by thatoddmailbox** [comment]
@medensqui Oh, I forgot. There was one other name for it ,but I can't pronounce it. It was like ingiznius something.

**Comment by thatoddmailbox** [comment]
@medensqui YAY I MADE A PAGE WITH SET UP INSTRUCTIONS! [CLICK ME](https://github.com/CoursesPlus/Labby/wiki/Setting-up-Labby).

**Comment by willbarkoff** [comment]
@thatoddmailbox does Labby let you login?

**Comment by thatoddmailbox** [comment]
@nywillb ....no..... it doesn't even have a database yet....

**Comment by willbarkoff** [comment]
@thatoddmailbox And on you planner, I am still not on the whitelist.

**Comment by thatoddmailbox** [comment]
@nywillb Sorry, I tpyo-d your username as c19wb. Try it now.

**Comment by willbarkoff** [comment]
Ok thanks. Also how about schoolwork.space

**Comment by thatoddmailbox** [comment]
@nywillb That's an option, though it would cost. The nice thing about a .me is that I have a free domain from GitHub student pack

**Comment by willbarkoff** [comment]
godaddy (even though you hate it) has it for $1.99. Cheap.

**Comment by thatoddmailbox** [comment]
@nywillb namecheap says $1.88.

**Comment by willbarkoff** [comment]
https://domains.google.com/registrar?s=schoolwork.space
http://www.1and1.com/domaincheckresult?__reuse=1445803825228&__lf=Static

See 1and1, its 99 cents.

**Comment by thatoddmailbox** [comment]
@nywillb I switched from 1&1 to namecheap. 1&1 is a very bad company; once, my site was down because an IP changed, but I couldn't update the records because 1&1 was busy being hacked.

...

Also, they took the maximum amount of time possible to switch my domain. I ended up talking to namecheap tech support and they said I had to wait for 1&1. I tried 1&1 tech support, they ignored me.

**Comment by thatoddmailbox** [comment]
@nywillb Also, the google domains page just gives me an error that they don't support .space domains.

**Comment by willbarkoff** [comment]
oh sorry.

**Comment by thatoddmailbox** [comment]
@nywillb It's ok.

**Comment by thatoddmailbox** [comment]
@medensqui @nywillb HELP ME PICK: [http://strawpoll.me/5832740](http://strawpoll.me/5832740)

**Comment by thatoddmailbox** [comment]
@medensqui @nywillb I didn't put StuderPlanner or the other weird mish-mash of a name on because duh. The Dalton ones I left out because I think I'm going to expand it outside of Dalton. "Workspace" was taken, so.

**Comment by thatoddmailbox** [comment]
@medensqui @nywillb KIDDING ABOUT THE STRAWPOLL! [USE THIS LINK PLEASE](https://usabilityhub.com/do/f46a31c6e80f/f336).

**Comment by medensqui** [comment]
@thatoddmailbox What about SchoolSpace?

**Comment by medensqui** [comment]
@thatoddmailbox ALSO CHANGE THE HOME PAGE. Also, when you figure out a name, please tell me so I can register it. Also tell me what to do

**Comment by willbarkoff** [comment]
How about school.space? I don't know if it is taken.

**Comment by medensqui** [comment]
@nywillb Maybe after the first year. But for now, we currently want to use .me so schoolspace.me would be the most helpful thing

**Comment by medensqui** [comment]
@thatoddmailbox So how would we integrate with other schools. So for example, if people at "John Doe School" (not a real school) wanted to use the thingy then how would we do that?

**Comment by thatoddmailbox** [comment]
@medensqui Currently, the poll is PlanHub vs. PlanPage. [Click for results](https://usabilityhub.com/tests/3f20c58bb998/results/f402cb8fb6b) [Click to participate](https://usabilityhub.com/do/3f20c58bb998/96a1).

I'm thinking we would have a generic account sign in/up page with a "Sign in with Dalton" button. If another school wanted a "Sign in with" button, they could ask us?

**Comment by thatoddmailbox** [comment]
@medensqui Also I'm probably going to register it. Eventually. If it ever gets decided.

**Comment by medensqui** [comment]
@thatoddmailbox That works. But most features (Labby, Schedules integration) wouldn't work with other schools. We would need more generic features.

**Comment by medensqui** [comment]
Also, Studer put in your schedule I want to present you with a new feature.

**Comment by medensqui** [comment]
@thatoddmailbox

**Comment by thatoddmailbox** [comment]
@medensqui That is true. There is the planbook and hw view, but.... 

What do you mean put in my schedule? Upload it here?

**Comment by medensqui** [comment]
@thatoddmailbox Yes

**Comment by willbarkoff** [comment]
@medensqui but anyone can see this

**Comment by medensqui** [comment]
@nywillb So?

**Comment by medensqui** [comment]
@nywillb Does anyone actually look at this?

**Comment by medensqui** [comment]
@thatoddmailbox Or just email but here is prefered

**Comment by thatoddmailbox** [comment]
@nywillb I don't really care if they have my schedule.
@medensqui 
![screenshot 2015-10-25 at 7 02 31 pm](https://cloud.githubusercontent.com/assets/1904587/10718508/1db4ab84-7b4b-11e5-9803-a753eef0f70b.png)

**Comment by willbarkoff** [comment]
@thatoddmailbox why are you on a chromebook?

**Comment by medensqui** [comment]
@nywillb He got one :cry:

**Comment by thatoddmailbox** [comment]
@nywillb because I have a chromebook. I switch between ChromeOS and Ubuntu (though with XFCE instead of Unity)

**Comment by thatoddmailbox** [comment]
@medensqui I also beat Portal and SuperTuxKart on it. So.

**Comment by medensqui** [comment]
@thatoddmailbox UPLOAD THY SCHEDULE

**Comment by thatoddmailbox** [comment]
@medensqui I DID GEEZ! How do you think @nywillb knew I was on a chromebook?

**Comment by medensqui** [comment]
@thatoddmailbox Where?

**Comment by thatoddmailbox** [comment]
@medensqui Here, I reuploaded it: 
![screenshot 2015-10-25 at 7 02 31 pm](https://cloud.githubusercontent.com/assets/1904587/10718524/8211364c-7b4b-11e5-9360-59fce8ad619b.png)

**Comment by medensqui** [comment]
@thatoddmailbox Nvm I'll just type it up and create a new issue. Btw, will you make a repos so we can make issues specific to this thing.

**Comment by thatoddmailbox** [comment]
@medensqui I will make a repo when I _HAVE A NAME FOR IT_!

...

still waiting for UsabilityHub. The current name choice is "PlanHub" or "PlanPage".

**Comment by medensqui** [comment]
@thatoddmailbox PlanHub. It's more of a central hub for schoolwork

**Comment by thatoddmailbox** [comment]
@medensqui Ok.
@nywillb pick one! PlanHub or PlanPage?

**Comment by medensqui** [comment]
@thatoddmailbox General idea of my idea.

Students don't get enough sleep.

Students can set ideally when they want to sleep and build a schedule that adapts to their target. They put in after-school activities, their schedule is synced. A hw schedule is suggested and they can adjust hw duration. They mark when they finish their hw. Less time than they thought = More Freetime or making up for the hw time that was earlier subtracted (you'll see in a second) More time than they thought = Subtraction from Freetime > Subtraction from Long-Term > Subtraction from Due Soon > Subtraction from sleep :cry:. This creates a day planner (or weekly view) that allows students to get as much sleep as they can without sacrificing schoolwork.

**Comment by medensqui** [comment]
@thatoddmailbox @nywillb So what do you think? Too ambitious? I think it would be like a drag and drop

**Comment by thatoddmailbox** [comment]
@medensqui oooooh that seems like a smart idea. The only problem is making students follow it... but if we could make it work, that would be _really_ cool. And make people like it over the plain-er daltonplanner.org.

Also, the "PlanHub" GitHub org name is taken. Any idea for some variation that would work? It doesn't allow PlanHub.me

**Comment by medensqui** [comment]
@thatoddmailbox There's no problem. If they don't follow it, they fall behind on long-term assignments. It helps what _EVERYONE_ is complaining about, aka sleep. And it allows people to put in freetime as after-school activities so people can put in breaks. It could also work w/ labby and schedule view.

**Comment by medensqui** [comment]
@thatoddmailbox Idk maybe PlanhUb  (it looks stupid but like U = you)

**Comment by thatoddmailbox** [comment]
@medensqui it's case insensitive. I registered @PlanHubMe and invited you both!

**Comment by medensqui** [comment]
@thatoddmailbox That works!

**Comment by medensqui** [comment]
@thatoddmailbox Should I register the domain?

**Comment by thatoddmailbox** [comment]
@medensqui No, I will. That way it's easier to connect to my server

**Comment by medensqui** [comment]
@thatoddmailbox Ok

**Comment by medensqui** [comment]
@thatoddmailbox Comment when you create it

**Comment by thatoddmailbox** [comment]
@medensqui REGISTERED! setting it up now...

**Comment by medensqui** [comment]
@thatoddmailbox So is what's on the server what's on the website? And how are we advertising this? Are we advertising this?

**Comment by thatoddmailbox** [comment]
@medensqui I own planhub.me but still have to move the site there. Also, IDK how we will advertise it. We shouldn't advertise _now_ (because it's only private beta), but later yes.

We should move this into the organization, so we stop spamming this issue. Do you want to create issues in the planhub repo?

**Comment by medensqui** [comment]
@thatoddmailbox I shall do that. 

Issue Request List:
(write comments tagging me)

**Comment by thatoddmailbox** [comment]
@medensqui Issue request list?

**Comment by thatoddmailbox** [comment]
@medensqui Oh I see. Umm.. make an advertisement issue

**Comment by medensqui** [comment]
@thatoddmailbox What issues should I post?

I have issues for general discussion and my idea

I could do bug reports?

**Comment by thatoddmailbox** [comment]
@medensqui bug reports would be a good idea.

**Comment by medensqui** [comment]
@thatoddmailbox Funny tidbit. Remember Scholar? Yeah Emlyn literally ripped off EasyBib https://www.iescholar.com/

**Comment by thatoddmailbox** [comment]
@medensqui EasyBib? that doesn't seem easybib-related to me.

**Comment by medensqui** [comment]
@thatoddmailbox 
![screen shot 2015-10-25 at 7 38 07 pm](https://cloud.githubusercontent.com/assets/12429395/10718738/f8967094-7b4f-11e5-879d-8608729ed896.png)

**Comment by thatoddmailbox** [comment]
@medensqui oh I see. They're both owned by the same parent company...
...

....ok then.

**Comment by willbarkoff** [comment]
@medensqui @thatoddmailbox It's called _Imagne Easy_.

**Comment by thatoddmailbox** [comment]
@nywillb *Imagine

Ok. Also, if you want to, please help us on @PlanHubMe - we're trying to find a logo and some other things.
